"""auto-generate

Revision ID: 184c0b89b835
Revises: 4363c5eef6fe
Create Date: 2022-01-01 15:31:48.950819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '184c0b89b835'
down_revision = '4363c5eef6fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
